### ISSUE TITLE
自动刷新会导致app异常退出

### ISSUE THREAD

**Issue by WongLu** [android-cjj/Android-MaterialRefreshLayout#29]
你好 , 非常感谢你开源的这个下拉刷新的库, 在设置materialRefreshLayout.autoRefresh();自动刷新的时候，会导致app异常退出。

**Comment by yuxingfafu** [comment]
你好,我周末开始用这个刷新库,发现有的时候会导致整个veiw在掉完接口后整个view会消失不见,等下才会自动出来,请问是否有遇到过这个情况

**Comment by WongLu** [comment]
@yuxingfafu  你好， 我也是刚用，只是在Activity里显示了多条数据，还发现View消失不见的问题。
